<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $unitKerjaList = [
            'Sekretariat Utama',
            'Pusat Data Geospasial',
            'Pusat Pengembangan Standar',
            'Pusat Informasi Geospasial',
            'Pusat Restorasi',
            'Pusat Survei Kependudukan',
            'Pusat Pemetaan Dasar',
        ];

        $agamaList = ['Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu'];
        $golonganList = ['I/a', 'I/b', 'I/c', 'I/d', 'II/a', 'II/b', 'II/c', 'III/a', 'III/b', 'III/c', 'III/d', 'IV/a', 'IV/b', 'IV/c', 'IV/d', 'IV/e'];
        $eselonList = [null, 'I', 'II', 'III', 'IV'];

        $kotaList = ['Jakarta', 'Bandung', 'Surabaya', 'Medan', 'Semarang', 'Makassar', 'Yogyakarta', 'Denpasar'];

        $employees = [
            [
                'nip' => '197503152000031001',
                'nama' => 'Budi Santoso',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1975-03-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Merdeka No. 10, Jakarta Pusat',
                'golongan' => 'IV/e',
                'eselon' => 'I',
                'jabatan' => 'Kepala Sekretariat Utama',
                'tempat_tugas' => 'Jakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Sekretariat Utama',
                'no_hp' => '081234567890',
                'npwp' => '12.345.678.9-001.000',
            ],
            [
                'nip' => '198008122002022002',
                'nama' => 'Siti Aminah',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1980-08-12',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Asia Afrika No. 25, Bandung',
                'golongan' => 'IV/d',
                'eselon' => 'II',
                'jabatan' => 'Kepala Bidang Pengembangan Standar',
                'tempat_tugas' => 'Bandung',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Pengembangan Standar',
                'no_hp' => '081234567891',
                'npwp' => '12.345.678.9-002.000',
            ],
            [
                'nip' => '198512152005011003',
                'nama' => 'Ahmad Rizky',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1985-12-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Tunjungan No. 45, Surabaya',
                'golongan' => 'III/c',
                'eselon' => 'III',
                'jabatan' => 'Kepala Bagian Data Geospasial',
                'tempat_tugas' => 'Surabaya',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Data Geospasial',
                'no_hp' => '081234567892',
                'npwp' => '12.345.678.9-003.000',
            ],
            [
                'nip' => '198205102008022004',
                'nama' => 'Dewi Sartika',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1982-05-10',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Gatot Subroto No. 100, Medan',
                'golongan' => 'IV/c',
                'eselon' => 'II',
                'jabatan' => 'Kepala Bidang Informasi Geospasial',
                'tempat_tugas' => 'Medan',
                'agama' => 'Kristen',
                'unit_kerja' => 'Pusat Informasi Geospasial',
                'no_hp' => '081234567893',
                'npwp' => '12.345.678.9-004.000',
            ],
            [
                'nip' => '197810202003012005',
                'nama' => 'Eko Prasetyo',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1978-10-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Pemuda No. 150, Semarang',
                'golongan' => 'III/d',
                'eselon' => 'IV',
                'jabatan' => 'Kepala Bidang Restorasi',
                'tempat_tugas' => 'Semarang',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Restorasi',
                'no_hp' => '081234567894',
                'npwp' => '12.345.678.9-005.000',
            ],
            [
                'nip' => '198302252010122006',
                'nama' => 'Fitri Handayani',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1983-02-25',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Pettarani No. 80, Makassar',
                'golongan' => 'III/b',
                'eselon' => 'III',
                'jabatan' => 'Kepala Seksi Survei Kependudukan',
                'tempat_tugas' => 'Makassar',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Survei Kependudukan',
                'no_hp' => '081234567895',
                'npwp' => '12.345.678.9-006.000',
            ],
            [
                'nip' => '198809152012032007',
                'nama' => 'Gunawan Wijaya',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-09-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Malioboro No. 55, Yogyakarta',
                'golongan' => 'III/a',
                'eselon' => 'IV',
                'jabatan' => 'Kepala Seksi Pemetaan Dasar',
                'tempat_tugas' => 'Yogyakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Pemetaan Dasar',
                'no_hp' => '081234567896',
                'npwp' => '12.345.678.9-007.000',
            ],
            [
                'nip' => '197612122005012008',
                'nama' => 'Hartono Gunawan',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '1976-12-12',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Raya Denpasar No. 200, Denpasar',
                'golongan' => 'IV/e',
                'eselon' => 'I',
                'jabatan' => 'Deputi Bidang Pengembangan Standar',
                'tempat_tugas' => 'Denpasar',
                'agama' => 'Hindu',
                'unit_kerja' => 'Pusat Pengembangan Standar',
                'no_hp' => '081234567897',
                'npwp' => '12.345.678.9-008.000',
            ],
            [
                'nip' => '198406182008022009',
                'nama' => 'Indah Permata',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1984-06-18',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Sudirman No. 120, Jakarta Selatan',
                'golongan' => 'IV/a',
                'eselon' => 'II',
                'jabatan' => 'Kepala Bidang Data Geospasial',
                'tempat_tugas' => 'Jakarta',
                'agama' => 'Katolik',
                'unit_kerja' => 'Pusat Data Geospasial',
                'no_hp' => '081234567898',
                'npwp' => '12.345.678.9-009.000',
            ],
            [
                'nip' => '198903122012011010',
                'nama' => 'Joko Widodo',
                'tempat_lahir' => 'Surakarta',
                'tanggal_lahir' => '1989-03-12',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Solo Raya No. 75, Surakarta',
                'golongan' => 'III/c',
                'eselon' => 'IV',
                'jabatan' => 'Kepala Seksi Informasi Geospasial',
                'tempat_tugas' => 'Surakarta',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Informasi Geospasial',
                'no_hp' => '081234567899',
                'npwp' => '12.345.678.9-010.000',
            ],
            [
                'nip' => '197907202003102011',
                'nama' => 'Kartika Sari',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1979-07-20',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Dago Atas No. 30, Bandung',
                'golongan' => 'IV/b',
                'eselon' => 'III',
                'jabatan' => 'Kepala Bagian Restorasi',
                'tempat_tugas' => 'Bandung',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Restorasi',
                'no_hp' => '081234567900',
                'npwp' => '12.345.678.9-011.000',
            ],
            [
                'nip' => '198611182010122012',
                'nama' => 'Lukman Hakim',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1986-11-18',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Gatot Subroto No. 150, Medan',
                'golongan' => 'III/b',
                'eselon' => 'IV',
                'jabatan' => 'Kepala Seksi Survei Kependudukan',
                'tempat_tugas' => 'Medan',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Survei Kependudukan',
                'no_hp' => '081234567901',
                'npwp' => '12.345.678.9-012.000',
            ],
            [
                'nip' => '198804052012032013',
                'nama' => 'Maria Kristina',
                'tempat_lahir' => 'Manado',
                'tanggal_lahir' => '1988-04-05',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Piere Tendean No. 90, Manado',
                'golongan' => 'III/a',
                'eselon' => 'IV',
                'jabatan' => 'Kepala Seksi Pemetaan Dasar',
                'tempat_tugas' => 'Manado',
                'agama' => 'Kristen',
                'unit_kerja' => 'Pusat Pemetaan Dasar',
                'no_hp' => '081234567902',
                'npwp' => '12.345.678.9-013.000',
            ],
            [
                'nip' => '197709182005012014',
                'nama' => 'Novi Anggraini',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '1977-09-18',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Khatib Sulaiman No. 60, Padang',
                'golongan' => 'IV/c',
                'eselon' => 'II',
                'jabatan' => 'Kepala Bidang Informasi Geospasial',
                'tempat_tugas' => 'Padang',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Informasi Geospasial',
                'no_hp' => '081234567903',
                'npwp' => '12.345.678.9-014.000',
            ],
            [
                'nip' => '198501202008022015',
                'nama' => 'Oscar Kurniawan',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1985-01-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Jendral Sudirman No. 200, Palembang',
                'golongan' => 'IV/a',
                'eselon' => 'II',
                'jabatan' => 'Kepala Bagian Data Geospasial',
                'tempat_tugas' => 'Palembang',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Data Geospasial',
                'no_hp' => '081234567904',
                'npwp' => '12.345.678.9-015.000',
            ],
            [
                'nip' => '198710252012032016',
                'nama' => 'Putri Ayu',
                'tempat_lahir' => 'Pekanbaru',
                'tanggal_lahir' => '1987-10-25',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Tuanku Tambusai No. 120, Pekanbaru',
                'golongan' => 'III/c',
                'eselon' => 'IV',
                'jabatan' => 'Kepala Seksi Informasi Geospasial',
                'tempat_tugas' => 'Pekanbaru',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Informasi Geospasial',
                'no_hp' => '081234567905',
                'npwp' => '12.345.678.9-016.000',
            ],
            [
                'nip' => '197406122005102017',
                'nama' => 'Qodar Salim',
                'tempat_lahir' => 'Banda Aceh',
                'tanggal_lahir' => '1974-06-12',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Teuku Umar No. 180, Banda Aceh',
                'golongan' => 'IV/e',
                'eselon' => 'I',
                'jabatan' => 'Kepala Bidang Restorasi',
                'tempat_tugas' => 'Banda Aceh',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Restorasi',
                'no_hp' => '081234567906',
                'npwp' => '12.345.678.9-017.000',
            ],
            [
                'nip' => '198308202010122018',
                'nama' => 'Ratna Sari',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1983-08-20',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Ir. H. Juanda No. 90, Bogor',
                'golongan' => 'IV/b',
                'eselon' => 'III',
                'jabatan' => 'Kepala Bagian Restorasi',
                'tempat_tugas' => 'Bogor',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Restorasi',
                'no_hp' => '081234567907',
                'npwp' => '12.345.678.9-018.000',
            ],
            [
                'nip' => '199005152012032019',
                'nama' => 'Sandi Pratama',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '1990-05-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Siliwangi No. 45, Cirebon',
                'golongan' => 'III/a',
                'eselon' => 'IV',
                'jabatan' => 'Kepala Seksi Pemetaan Dasar',
                'tempat_tugas' => 'Cirebon',
                'agama' => 'Islam',
                'unit_kerja' => 'Pusat Pemetaan Dasar',
                'no_hp' => '081234567908',
                'npwp' => '12.345.678.9-019.000',
            ],
            [
                'nip' => '19730305200012020',
                'nama' => 'Taufik Hidayat',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1973-03-05',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Basuki Rahmat No. 110, Malang',
                'golongan' => 'IV/e',
                'eselon' => 'I',
                'jabatan' => 'Kepala Sekretariat Utama',
                'tempat_tugas' => 'Malang',
                'agama' => 'Islam',
                'unit_kerja' => 'Sekretariat Utama',
                'no_hp' => '081234567909',
                'npwp' => '12.345.678.9-020.000',
            ],
        ];

        foreach ($employees as $employee) {
            DB::table('employees')->insert([
                'nip' => $employee['nip'],
                'nama' => $employee['nama'],
                'tempat_lahir' => $employee['tempat_lahir'],
                'tanggal_lahir' => $employee['tanggal_lahir'],
                'jenis_kelamin' => $employee['jenis_kelamin'],
                'alamat' => $employee['alamat'],
                'golongan' => $employee['golongan'],
                'eselon' => $employee['eselon'],
                'jabatan' => $employee['jabatan'],
                'tempat_tugas' => $employee['tempat_tugas'],
                'agama' => $employee['agama'],
                'unit_kerja' => $employee['unit_kerja'],
                'no_hp' => $employee['no_hp'],
                'npwp' => $employee['npwp'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ 20 employees seeded successfully!');
        $this->command->info('📊 Data pegawai berhasil ditambahkan.');
    }
}
